### ISSUE TITLE
Move towards eliminating .env requirement for dev,rc,experts

### ISSUE THREAD

**Issue by qjhart** [ucd-library/rp-ucd-deployment#9]
The plan for experts will continue to be routing all requests through a single router (router.experts.library.ucdavis.edu).  I'd like to continue routing via different ports for our servers, and because of the number of installs, we will potentially be running two instances (like dev,rc) on one backend (eg. blue).

Since we have seperate docker-compose for each stage, I suggest that we update those compose files, for the default values for server names and ports.  So we'd have something like:

```yml
  gateway:
    image: ucdlib/rp-ucd-gateway:dev
    environment:
      - ${SERVER_URL:-https://dev.experts.library.ucdavis.edu}
    ports:
      - ${HOST_PORT:-3006}:3000
    restart: on-failure
```

Also, we'd potentially limit the ports we'd promote to the OS on rc and prod.  

The only downside would be developers testing different installs,  but since the .env would still be read, that could be adjusted there, without modifing the docker-compose files.
